name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Refresh tags and categories for the Solodit
      id: refreshRequest
      run: |
        curl -v -k -X POST https://solodit-admin.cyfrin.dev/api/general/refresh_tag_category/ \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "email=${{ secrets.SOLODIT_USER }}" \
        -d "password=${{ secrets.SOLODIT_PASSWORD }}"
    - name: Show Response of Refreshing Tags and Categories
      run: |
        echo ${{ steps.refreshRequest.outputs.response }}
    - name: Refresh protocol fork information
      id: refreshForkInfoRequest
      run: |
        curl -v -k -X POST https://solodit-admin.cyfrin.dev/api/general/refresh_forked_protocol/ \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "email=${{ secrets.SOLODIT_USER }}" \
        -d "password=${{ secrets.SOLODIT_PASSWORD }}"
    - name: Show Response of Refreshing Protocol Fork Informations
      run: |
        echo ${{ steps.refreshForkInfoRequest.outputs.response }}
    - name: Import reports
      id: importReportRequest
      run: |
        curl -v -k -X POST https://solodit-admin.cyfrin.dev/api/general/import_reports/ \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "email=${{ secrets.SOLODIT_USER }}" \
        -d "password=${{ secrets.SOLODIT_PASSWORD }}"
    - name: Show Response of Importing Reports
      run: |
        echo ${{ steps.importReportRequest.outputs.response }}
    - name: Refresh bug bounties
      id: refreshBugBounties
      run: |
        curl -v -k -X POST https://solodit-admin.cyfrin.dev/api/general/refresh_bug_bounties/ \
        -H "Content-Type: application/x-www-form-urlencoded" \
        -d "email=${{ secrets.SOLODIT_USER }}" \
        -d "password=${{ secrets.SOLODIT_PASSWORD }}"
    - name: Show Response of Refreshing Bug bounties
      run: |
        echo ${{ steps.refreshBugBounties.outputs.response }}
